apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /gitlab-data
    server: 10.248.28.51
  persistentVolumeReclaimPolicy: Recycle